AntiFraudProjsect/urls.py
# Copyright 2020 Mikhail Dolbnin dolbnin.n@gmail.com

"""AntiFraudProjsect URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('fraud_monitor/', include('fraud_monitor.urls')),
    path('', RedirectView.as_view(url='fraud_monitor/', permanent=True)),
]

from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

fraud_monitor/urls.py
# Copyright 2020 Mikhail Dolbnin dolbnin.n@gmail.com

from django.conf.urls import url
from django.urls import path, include
from django.views.generic import RedirectView
from . import views

app_name = 'fraud_monitor'

urlpatterns = [
    url('upload/', views.upload, name='upload'),
    url(r'^$', views.index, name='index'),
    url('stats/', views.stats, name='stats'),
]

fraud_monitor/models.py
# Copyright 2020 Mikhail Dolbnin dolbnin.n@gmail.com

from django.db import models

class Transaction(models.Model):
    TransactionID = models.CharField(max_length = 25)
    TransactionAmt = models.FloatField()
    Card1 = models.FloatField()
    Card2 = models.FloatField()
    isFraud = models.BooleanField(default=False)
    Card6 = models.CharField(max_length = 10)

    def __str__(self):
        return self.TransactionID

    def getStatus(self):
        return self.isFraud

fraud_monitor/views.py
# Copyright 2020 Mikhail Dolbnin dolbnin.n@gmail.com

import json
from django.shortcuts import render
from django.template import loader, Context
from django.http import HttpResponse
from .models import Transaction


def index(request):
    last_transaction = Transaction.objects.all()[::-1]
    return render(
        request,
        './fraud_monitor/index.html',
        {'last_transaction' : last_transaction}
        )


def upload(request):
    if request.method == "POST":
        data = request.body.decode('utf8')
        data = json.loads(data)
        element = Transaction(TransactionID = data['id'],
                            TransactionAmt = data['amt'],
                            Card1 = data['card1'],
                            Card2 = data['card2'],
                            isFraud = data['fraud'],
                            Card6 = data['card6']
        )
        element.save()
        print(element, " is saved")
        return HttpResponse(str(element) +" is saved")
    else:
        return HttpResponse("no")


def stats(request):
    last_transaction = Transaction.objects.all()
    legal = len(last_transaction.filter(isFraud = False))
    fraud = len(last_transaction.filter(isFraud = True))
    return render(
    request,
    './fraud_monitor/stats.html',
    {'legal' : legal, 'fraud' : fraud}
    )

templates/base_generic.html
<html>
  <head>
    {% block title %}<title>FPS</title>{% endblock %}
    {% block head %}
    {% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>
  <body>
    {% block content %}
    {% endblock %}
  </body>
</html>

templates/fraud_monitor/base_generic.html
<html>
  <head>
    {% block title %}<title>FPS</title>{% endblock %}
    {% block head %}
    {% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <style media="screen">
      .sidebar-nav {
          margin-top: 20px;
          padding: 0;
          list-style: none;
      }
      .test {
        text-align: center;
      }
    </style>
  </head>
  <body>
    {% block content %}
    <div class="test">
      <h1>FraudPS</h1>
      <h2>Auth</h2>
    </div>
    <div class="">

    </div>
    {% endblock %}
  </body>
</html>

templates/fraud_monitor/index.html
{% extends "base_generic.html" %}

{% block title %}
<title>FPS</title>
{% endblock %}

{% block head %}
<style>
    #myInput {
    width: 100%;
    font-size: 20px;
    padding: 12px 20px 12px 20px;
    border: 1px solid #ddd;
    margin-bottom: 12px;
    }
    .row.content {height: auto}
    .sidenav {
      padding-top: 20px;
      background-color: #f1f1f1;
      height: 100%;
    }

    /* On small screens, set height to 'auto' for sidenav and grid */
    @media screen and (max-width: 767px) {
      .sidenav {
        height: auto;
        padding: 15px;
      }
      .row.content {height:auto;}
    }
  </style>
{% endblock %}

{% block content %}
<div class="navbar navbar-inverse sticky-top">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Fraud Prediction System</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="{% url 'fraud_monitor:index' %}">Home</a></li>
      <li class=""><a href="{% url 'fraud_monitor:stats' %}">Stats</a></li>
      <li class=""><a href="{% url 'admin:index' %}">Admins</a></li>
    </ul>
</div>
<div class="container-fluid text-center">
<div class="row content">
  <div class="col-sm-2 sidenav">
  </div>
  <div class="col-sm-8 text-left">
    <h2>Transaction logs</h2>
    <input type="text" id="myInput" onkeyup="myFunction()" placeholder="Search for id..">
    <table class="table" id="myTable">
    <thead>
      <tr>
        <th>TransactionID</th>
        <th>TransactionAmt</th>
        <th>Card1</th>
        <th>Card2</th>
        <th>Card6</th>
      </tr>
    </thead>
    <tbody>
      {% if last_transaction %}

        {% for a in last_transaction %}

          {% if a.isFraud %}
            <tr class="danger">
          {% else %}
            <tr class="success">
          {% endif %}
              <td>{{a.TransactionID}}</td>
              <td>{{a.TransactionAmt}}</td>
              <td>{{a.Card1}}</td>
              <td>{{a.Card2}}</td>
              <td>{{a.Card6}}</td>
            </tr>
        {% endfor %}

      {% endif %}
    </tbody>
  </table>

  <script>
function myFunction() {
  var input, filter, table, tr, td, i, txtValue;
  input = document.getElementById("myInput");
  filter = input.value.toUpperCase();
  table = document.getElementById("myTable");
  tr = table.getElementsByTagName("tr");
  for (i = 0; i < tr.length; i++) {
    td = tr[i].getElementsByTagName("td")[0];
    if (td) {
      txtValue = td.textContent || td.innerText;
      if (txtValue.toUpperCase().indexOf(filter) > -1) {
        tr[i].style.display = "";
      } else {
        tr[i].style.display = "none";
      }
    }
  }
}
</script>

  </div>
  <div class="col-sm-2 sidenav">
    <a href="{% url 'fraud_monitor:index' %}" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Refresh</a>
  </div>
</div>
</div>
{% endblock %}

templates/fraud_monitor/stats.html
{% extends "base_generic.html" %}

{% block title %}
<title>FPS</title>
{% endblock %}

{% block head %}
<script src="https://code.highcharts.com/highcharts.js"></script>
<style>
    #myInput {
    width: 100%;
    font-size: 20px;
    padding: 12px 20px 12px 20px;
    border: 1px solid #ddd;
    margin-bottom: 12px;
    }
    .row.content {height: auto}
    .sidenav {
      padding-top: 20px;
      background-color: #f1f1f1;
      height: 100%;
    }

    /* On small screens, set height to 'auto' for sidenav and grid */
    @media screen and (max-width: 767px) {
      .sidenav {
        height: auto;
        padding: 15px;
      }
      .row.content {height:auto;}
    }
  </style>
{% endblock %}

{% block content %}
<div class="navbar navbar-inverse sticky-top">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Fraud Prediction System</a>
    </div>
    <ul class="nav navbar-nav">
      <li class=""><a href="{% url 'fraud_monitor:index' %}">Home</a></li>
      <li class="active"><a href="{% url 'fraud_monitor:stats' %}">Stats</a></li>
      <li class=""><a href="{% url 'admin:index' %}">Admins</a></li>
    </ul>
</div>
<div class="container-fluid text-center">
<div class="row content">
  <div class="col-sm-2 sidenav">
  </div>
  <div class="col-sm-8 text-left">
    <h2>Transaction stats</h2>
    <div id="container1"></div>
    <script>
        Highcharts.chart('container1', {
          chart: {
              plotBackgroundColor: null,
              plotBorderWidth: null,
              plotShadow: false,
              type: 'pie'
          },
          title: {
              text: 'Ratio between fraud and legal operations'
          },
          tooltip: {
              pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
          },
          accessibility: {
              point: {
                  valueSuffix: '%'
              }
          },
          plotOptions: {
              pie: {
                  allowPointSelect: true,
                  cursor: 'pointer',
                  dataLabels: {
                      enabled: false
                  },
                  showInLegend: true
              }
        },
          series: [{
              name: 'Status',
              colorByPoint: true,
              data: [{
                  name: 'Legal',
                  y: {{legal}},
                  sliced: true,
                  selected: true
              }, {
                  name: 'Fraud',
                  y: {{fraud}}
              }]
          }]
      });
    </script>
  </div>
  <div class="col-sm-2 sidenav">
    <a href="{% url 'fraud_monitor:index' %}" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Refresh</a>
  </div>
</div>
</div>
{% endblock %}